---
abstract: 'Perl wrapper for The MovieDB API'
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
build_requires:
  Test::More: 0
  version: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.113640'
keywords:
  - tmdb
  - movie
  - imdb
  - api
  - themoviedb
  - moviedb
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TMDB
provides:
  TMDB:
    file: lib/TMDB.pm
    version: 0.03
  TMDB::Movie:
    file: lib/TMDB/Movie.pm
    version: 0
  TMDB::Person:
    file: lib/TMDB/Person.pm
    version: 0
  TMDB::Search:
    file: lib/TMDB/Search.pm
    version: 0
  TMDB::Session:
    file: lib/TMDB/Session.pm
    version: 0
requires:
  Encode: 0
  JSON::Any: 0
  LWP::UserAgent: 0
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=TMDB
  homepage: https://github.com/mithun/perl-tmdb
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mithun/perl-tmdb.git
version: 0.03
